name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deploy only when there's a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Get the code from your repository

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Set up Node.js environment
      with:
        node-version: '14'  # You can change this to whatever version you need

    - name: Install dependencies
      run: npm install  # Install project dependencies

    - name: Build the project
      run: npm run build -- --configuration production --base-href /portfoliowebsite/  # Build the project

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Action for GitHub Pages deployment
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token to push to gh-pages
        publish_dir: ./dist/portfoliowebsite  # Folder where the build files are
